name: libertime
description: A new Flutter application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  logging: ^0.11.4
  flutter_bloc: ^6.1.3

  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1

  flutter_riverpod: ^0.12.2

  share_ui:
    path: ./libraries/share_ui
  common:
    path: ./libraries/common
  features:
    path: ./features

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.4
  build_runner:
  # flutter packages pub run build_runner watch (--delete-conflicting-outputs)
  # flutter pub upgrade
  # flutter packages pub run build_runner build (--delete-conflicting-outputs)

flutter_icons:
  image_path: "assets/launcher/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/heart.riv
  fonts:

    - family:  LiberMe
      fonts:
       - asset: assets/fonts/IconFonts.ttf