name: libertime
description: A new Flutter application.
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get_it: ^5.0.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  flutter_fimber: ^0.4.4
  logging: ^0.11.4
  freezed_annotation: ^0.12.0
  moor_flutter: ^3.1.0
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0

  share_ui:
    path: ./share_ui
  auth:
    path: ./auth
  home:
    path: ./home
  explore:
    path: ./explore
  message:
    path: ./message
  setting:
    path: ./setting
  notification:
    path: ./notification

  share_module:
    path: ./share_module

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter
  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.10.9 #-> flutter packages pub run build_runner watch --delete-conflicting-outputs
  chopper_generator: ^3.0.6
  freezed: ^0.12.3
  moor_generator: ^3.4.0

flutter_icons:
  image_path: "assets/launcher/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
  fonts:
    - family: Raleway
      fonts:
       - asset: assets/fonts/Roboto-Regular.ttf
       - asset: assets/fonts/Roboto-Medium.ttf
         style: normal

    - family:  LiberMe
      fonts:
       - asset: assets/fonts/IconFonts.ttf