name: libertime
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Google Firebase Store
  cloud_firestore: ^0.13.5

  # Swap the connectivity package for this
  data_connection_checker: ^0.3.4
  # Service locator
  get_it: ^4.0.2
  # Bloc for state management
  flutter_bloc: ^4.0.0
  # Value equality
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  #connectivity: ^0.4.3+7
  chopper: ^3.0.1
  # Secure store cache
  flutter_secure_storage: ^3.3.1+1
  # timber log
  fimber: ^0.4.0
  # make work with union easier
  freezed_annotation: ^0.7.1
  #room db
  moor_flutter: ^2.1.1


  splash:
    path: ./splash

  widget:
    path: ./widget

  login:
    path: ./login

  core_packages:
    path: ./core

dev_dependencies:
  lint: ^1.1.1
  flutter_test:
    sdk: flutter
  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.7.2 #-> flutter packages pub run build_runner watch --delete-conflicting-outputs
  chopper_generator: ^3.0.1
  freezed: ^0.10.5
  moor_generator: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/launcher/ic_launcher.png"
  android: true
  ios: true
  #image_path_ios: "assets/launcher/ic_launcher.png"
  #image_path_android: "assets/launcher/icon.png"
  #adaptive_icon_background: "assets/launcher/background.png"
  #adaptive_icon_foreground: "assets/launcher/foreground.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/materials/
    - assets/launcher/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
       - asset: assets/fonts/Raleway-Regular.ttf
       - asset: assets/fonts/Raleway-Thin.ttf
         style: normal

    - family:  Iconfont
      fonts:
       - asset: assets/fonts/Iconfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages