name: share_ui
description: Awesome shared widgets package.
version: 0.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^4.1.1+1
  nb_utils: ^3.3.0+8
  cached_network_image: ^2.3.3

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter

flutter:
