name: widget
description: Awesome widgets package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #beauty bottom bar
  bottom_navy_bar: ^5.2.2

  flutter_spinkit: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
