/// Flutter icons Iconfont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconfont
///      fonts:
///       - asset: fonts/Iconfont.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class Iconfont {
  Iconfont._();

  static const _kFontFam = 'Iconfont';

  static const IconData a_z = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData recents = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData favorite = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData notifications = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData done = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData arrow_down = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData arrow_back = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData arrow_forward = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData add = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData in_progress = IconData(0xe834, fontFamily: _kFontFam);
}
