name: features
description: features module
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  logging: ^0.11.4
  dartz: ^0.9.2
  chopper: ^3.0.6
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  verify: ^1.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  built_value: ^7.1.0
  dart_nats: ^0.1.8
  flutter_screenutil: ^4.0.2+8
  flutter_tindercard: ^0.2.0
  rive: ^0.6.7
  google_maps_flutter: ^1.2.0
  location: ^3.2.4
  flutter_facebook_auth: ^2.0.2

  common:
    path: ../libraries/common
  share_ui:
    path: ../libraries/share_ui
  database:
    path: ../infrastructure/database

dependency_overrides:
  analyzer: ^0.41.2

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.1.0
  build_runner:
  chopper_generator: ^3.0.3
  freezed: ^0.12.2

flutter: