name: features
description: features module
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  logging: ^0.11.4
  dartz: ^0.9.2
  flutter_bloc: ^6.1.3
  verify: ^1.1.1
  freezed_annotation: ^0.12.0
  dart_nats: ^0.1.8
  flutter_screenutil: ^4.0.2+8
  flutter_tindercard: ^0.2.0
  rive: ^0.6.7
  google_maps_flutter: ^1.2.0
  location: ^3.2.4
  flutter_riverpod: ^0.12.2

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0

  google_sign_in:  ^4.5.9
  flutter_facebook_auth: ^2.0.2

  common:
    path: ../libraries/common
  share_ui:
    path: ../libraries/share_ui
  network:
    path: ../libraries/network
  database:
    path: ../infrastructure/database

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.12.7

flutter: