name: share_module
description: Shared package
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Value equality
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.9.2

  chopper: ^3.0.6
  
  freezed_annotation: ^0.12.0

  #Date format
  intl: ^0.16.1

dev_dependencies:
  lint: ^1.3.0
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.9
  freezed: ^0.12.3

flutter:
